package materiel.portable;

import materiel.GenericResponse;
import materiel.ResourceNotFoundException;
import materiel.emprunt.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.Optional;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/api") // This means URL's start with /api (after Application path)
/* CrossOrigin(origins = "http://localhost:3000")*/
public class PortableController {
    @Autowired // This means to get the bean called portableRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PortableRepository portableRepository;

    @Autowired
    private UserRepository userRepository;


    // Get all Portables
    @GetMapping(path = "/portabletypes")
    public @ResponseBody
    Iterable<Portabletype> getAllPortables() {
        // This returns a JSON or XML with the portables
        return portableRepository.findAll();
    }

    // Get a single Portabletype
    @GetMapping("/portabletypes/{id}")
    public @ResponseBody
    Portabletype getPortableById(@PathVariable(value = "id") int portableId) {
        Optional<Portabletype> portable = portableRepository.findById(portableId);
        if (portable == null || portable.get() == null)
            throw new ResourceNotFoundException("Portabletype", "id", portableId);

        return portable.get();
    }

    // Add a new Portabletype
    @PostMapping(path = "/portabletypes") // Map ONLY POST Requests
    public @ResponseBody
    Portabletype addNewPortable(@Valid @RequestBody Portabletype portable) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return portableRepository.save(portable);
    }

    // Update a Portabletype
    @PutMapping("/portabletypes/{id}")
    public @ResponseBody
    Portabletype updatePortable(@PathVariable(value = "id") int portableId,
                                @Valid @RequestBody Portabletype portableDetails) {

        Portabletype portable = portableRepository.findById(portableId)
                .orElseThrow(() -> new ResourceNotFoundException("Portabletype", "id", portableId));

        // Pour être sûr
        portableDetails.setId(portable.getId());

        return portableRepository.save(portableDetails);
    }

    // Delete a Portabletype
    @DeleteMapping(path = "/portabletypes/{id}")
    public @ResponseBody
    ResponseEntity<?> deletePortable(@PathVariable(value = "id") int portableId) {
        Portabletype portable = portableRepository.findById(portableId)
                .orElseThrow(() -> new ResourceNotFoundException("Portabletype", "id", portableId));

        portableRepository.delete(portable);

        return ResponseEntity.ok().body(new GenericResponse(true, "Suppression effectuée"));
    }
}
